# REINVENT4 TOML reinforcement learning for antibiotic design

run_type = "staged_learning"
device = "cuda:0"  # set torch device e.g. "cpu"
tb_logdir = "tb_logs"  # name of the TensorBoard logging directory
json_out_config = "_staged_learning.json"  # write this TOML to JSON

[parameters]

summary_csv_prefix = "staged_learning"  # prefix for the CSV file
use_checkpoint = false  # if true read diversity filter from agent_file
purge_memories = false  # if true purge all diversity filter memories after each stage

## Reinvent
prior_file = "../../priors/reinvent.prior"
agent_file = "../../priors/reinvent.prior"

batch_size = 50          # network

unique_sequences = true  # if true remove all duplicates raw sequences in each step
                         # only here for backward compatibility
randomize_smiles = true  # if true shuffle atoms in SMILES randomly

tb_isim = false  # track iSIM similarity in TensorBoard


[learning_strategy]

type = "dap"      # dap: only one supported
sigma = 128       # sigma of the RL reward function
rate = 0.0001     # for torch.optim


[diversity_filter]  # optional, comment section out or remove if unneeded
                    # NOTE: also memorizes all seen SMILES

type = "IdenticalMurckoScaffold" # IdenticalTopologicalScaffold,
                                 # ScaffoldSimilarity, PenalizeSameSmiles
bucket_size = 25                 # memory size in number of compounds
minscore = 0.4                   # only memorize if this threshold is exceeded
minsimilarity = 0.4              # minimum similarity for ScaffoldSimilarity
penalty_multiplier = 0.5         # penalty factor for PenalizeSameSmiles


[[stage]]

chkpt_file = 'antibiotics.chkpt'  # name of the checkpoint file, can be reused as agent

termination = "simple"  # termination criterion for this stage
max_score = 1.0  # terminate if this total score is exceeded
min_steps = 200  # run for at least this number of steps
max_steps = 200  # terminate entire run when exceeded

[stage.scoring]
type = "geometric_mean"  # aggregation function

[[stage.scoring.component]]
[stage.scoring.component.MolecularWeight]
[[stage.scoring.component.MolecularWeight.endpoint]]
name = "MolecularWeight"
weight = 1
transform.type = "left_step"
transform.low = 600.0

[[stage.scoring.component]]
[stage.scoring.component.SAScore]
[[stage.scoring.component.SAScore.endpoint]]
name = "SAScore"
weight = 1
transform.type = "left_step"
transform.low = 4

[[stage.scoring.component]]
[stage.scoring.component.Solubility]
[[stage.scoring.component.Solubility.endpoint]]
name = "Solubility"
weight = 1
transform.type = "right_step"
transform.high = -4

[[stage.scoring.component]]
[stage.scoring.component.Antibiotic]
[[stage.scoring.component.Antibiotic.endpoint]]
name = "Antibiotic"
weight = 5
